version: '3.8'
services:
  mydatabase:
    image: mysql
    container_name: mydatabase
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'contacts-mysql'
      MYSQL_USER: 'contacts-mysql'
      MYSQL_PASSWORD: '123456'
    ports:
      - '33306:3306'

  mybackend:
    build: 
      context: ./api
    depends_on:
      - mydatabase
    environment:
      MYSQL_HOST_IP: mydatabase
      MYSQL_USER: root
      MYSQL_DATABASE: contacts-mysql
      MYSQL_PASSWORD: 123456
    ports:
      - 5000:5000
    volumes:
      - ./api:/api

  myfrontend:
    build: 
      context: ./web
    ports:
      - 3000:80
    volumes:
      - ./web:/web

volumes:
  mysql_srv:
    driver: local